# Application bindings
$terminal = uwsm app -- $TERMINAL
$browser = omarchy-launch-browser

bindd = SUPER SHIFT, RETURN, Terminal, exec, $terminal --dir="$(omarchy-cmd-terminal-cwd)"
bindd = SUPER SHIFT, F, File manager, exec, uwsm app -- nautilus --new-window
bindd = SUPER SHIFT, B, Browser, exec, $browser
bindd = SUPER SHIFT ALT, B, Browser (private), exec, $browser --private
bindd = SUPER SHIFT, M, Music, exec, mpv --shuffle "$(cat ~/.alice/data/music | walker --dmenu -p 'Music' --width 800 --height 800)"
bindd = SUPER SHIFT, N, Editor, exec, omarchy-launch-editor

bind = SUPER, D, exec, wayscriber --daemon-toggle
bind = SUPER SHIFT, D, exec, wayscriber --daemon-toggle --freeze

bindd = SUPER SHIFT, O, Obsidian, exec, omarchy-launch-or-focus obsidian "uwsm app -- obsidian -disable-gpu --enable-wayland-ime"

bindd = SUPER SHIFT, W, Impala, exec, omarchy-launch-wifi

# If your web app url contains #, type it as ## to prevent hyperland treat it as comments
# bindd = SUPER SHIFT, A, ChatGPT, exec, omarchy-launch-webapp "https://chatgpt.com"
# bindd = SUPER SHIFT ALT, A, Grok, exec, omarchy-launch-webapp "https://grok.com"
# bindd = SUPER SHIFT, C, Calendar, exec, omarchy-launch-webapp "https://app.hey.com/calendar/weeks/"
# bindd = SUPER SHIFT, E, Email, exec, omarchy-launch-webapp "https://app.hey.com"
# bindd = SUPER SHIFT, Y, YouTube, exec, omarchy-launch-or-focus-webapp YouTube "https://youtube.com/"
# bindd = SUPER SHIFT ALT, G, WhatsApp, exec, omarchy-launch-or-focus-webapp WhatsApp "https://web.whatsapp.com/"
# bindd = SUPER SHIFT CTRL, G, Google Messages, exec, omarchy-launch-or-focus-webapp "Google Messages" "https://messages.google.com/web/conversations"
# bindd = SUPER SHIFT, X, X, exec, omarchy-launch-webapp "https://x.com/"
# bindd = SUPER SHIFT ALT, X, X Post, exec, omarchy-launch-webapp "https://x.com/compose/post"
#
# Overwrite existing bindings, like putting Omarchy Menu on Super + Space
# unbind = SUPER SHIFT, SPACE


# Full screen screenshot → save + copy + notify
bind = SHIFT CTRL, S, exec, grim ~/Pictures/Screenshots/screenshot-$(date +%F_%H-%M-%S).png && notify-send "📸 Area Screenshot Saved" "Saved to ~/Pictures/Screenshots/"
bind = SHIFT SUPER, S, exec, grim ~/Pictures/Screenshots/screenshot-$(date +%F_%H-%M-%S).png && notify-send "📸 Area Screenshot Saved" "Saved to ~/Pictures/Screenshots/"

# wipe any J/K that were set earlier
unbind = SUPER, J
unbind = SUPER, K

# tiling vimifie
bindd = SUPER SHIFT, J, Toggle split, togglesplit, # dwindle
bindd = SUPER SHIFT, K, Show key bindings, exec, omarchy-menu-keybindings

bindd = SUPER, H, Move focus left, movefocus, l
bindd = SUPER, L, Move focus right, movefocus, r
bindd = SUPER, K, Move focus up, movefocus, u
bindd = SUPER, J, Move focus down, movefocus, d 

unbind = SUPER CTRL, S
bind = SUPER CTRL, S, swapactiveworkspaces, eDP-2 HDMI-A-1

# Swap active window with the one next to it with SUPER + SHIFT + arrow keys
bindd = SUPER CTRL, h, Swap window to the left, swapwindow, l
bindd = SUPER CTRL, l, Swap window to the right, swapwindow, r
bindd = SUPER CTRL, k, Swap window up, swapwindow, u
bindd = SUPER CTRL, j, Swap window down, swapwindow, d


bind = SUPER, 0, workspace, 10
bindd = SUPER SHIFT, code:19, Move window to workspace 10, movetoworkspace, 10

unbind = SUPER SHIFT, C
bindd = SUPER SHIFT, C, Calculator, exec, gnome-calculator
unbind = SUPER SHIFT, T
bindd = SUPER SHIFT, T, Timer, exec, bash /home/neros/.config/play-timer/play-timer.sh

bindd = SUPER, RETURN, Relitive Command, exec, python3 ~/.alice/scripts/relitive_commands.py 
