# Learn how to configure Hyprland: https://wiki.hyprland.org/Configuring/
#
# # Use defaults Omarchy defaults (but don't edit these directly!)
source = ~/.config/hypr/default/hypr/bindings/media.conf
source = ~/.config/hypr/default/hypr/bindings/clipboard.conf
source = ~/.config/hypr/default/hypr/bindings/tiling-v2.conf
source = ~/.config/hypr/default/hypr/bindings/utilities.conf
source = ~/.config/hypr/default/hypr/envs.conf
source = ~/.config/hypr/default/hypr/looknfeel.conf
source = ~/.config/hypr/default/hypr/input.conf
#TODO fix windowrules problem so that i can uses the windows.conf again
source = ~/.config/hypr/default/hypr/windows.conf 
source = ~/.config/omarchy/current/theme/hyprland.conf
#
# # Change your own setup in these files (and overwrite any settings from defaults!)
source = ~/.config/hypr/monitors.conf
source = ~/.config/hypr/input.conf
source = ~/.config/hypr/bindings.conf
source = ~/.config/hypr/envs.conf
source = ~/.config/hypr/looknfeel.conf
source = ~/.config/hypr/autostart.conf
source = ~/.config/hypr/pixie.conf
#
#
# ~/.config/hypr/hyprland.conf
env = XCURSOR_PATH,~/.icons:/usr/share/icons
env = HYPRCURSOR_THEME,Bibata-Modern-Ice
env = HYPRCURSOR_SIZE,20
env = XCURSOR_THEME,Bibata-Modern-Ice
env = XCURSOR_SIZE,20

# NVIDIA environment variables
env = NVD_BACKEND,direct
env = LIBVA_DRIVER_NAME,nvidia
env = __GLX_VENDOR_LIBRARY_NAME,nvidia
env = AQ_DRM_DEVICES,/dev/dri/card2:/dev/dri/card1

input {
    kb_options = ctrl:nocaps
}# Custom curve for snappy animations
