# JetBrains windows default size
# windowrule = size 50% 50%, class:(.*jetbrains.*)$, title:^$
# new syntax
windowrule = match:class (.*jetbrains.*)$ match:title ^$, size 50% 50%

# Fix tab dragging (tab titles are just one space)
# windowrule = noinitialfocus, class:^(.*jetbrains.*)$, title:^\\s$
# new syntax
windowrule =  match:class ^(.*jetbrains.*)$ match:title ^\\s$, no_initial_focus on

# Allow dialogs (like "Send usage statistics") to be focusable and clickable
# windowrule = unset,nofocus,class:^(.*jetbrains.*)$,title:^$
# new syntax
windowrule = match:class ^(.*jetbrains.*)$ match:title ^$, no_focus on # Needs to uses unset but don't know how

# windowrule = unset,noinitialfocus,class:^(.*jetbrains.*)$,title:^$
