# Picture-in-picture overlays
# windowrule = tag +pip, title:(Picture.?in.?[Pp]icture)
# new syntax
windowrule =match:title (Picture.?in.?[Pp]icture), tag +pip


# windowrule = float, tag:pip
# new syntax
windowrule = match:tag pip, float on

# windowrule = pin, tag:pip
# new syntax
windowrule = match:tag pip, pin on

# windowrule = size 600 338, tag:pip
# new syntax
windowrule = match:tag pip, size 600 338

# windowrule = keepaspectratio, tag:pip
# new syntax
windowrule = match:tag pip, keep_aspect_ratio on

# windowrule = noborder, tag:pip
# new syntax
windowrule = match:tag pip, border_size 0, decorate off

# windowrule = opacity 1 1, tag:pip
# new syntax
windowrule =match:tag pip, opacity 1 1

# windowrule = move 100%-w-40 4%, tag:pip
# new syntax
windowrule = match:tag pip, move 100%-w-40 4%
