# windowrule = fullscreen, class:com.libretro.RetroArch
# new syntax
windowrule = match:class com.libretro.RetroArch, fullscreen on

# windowrule = opacity 1 1, class:com.libretro.RetroArch
# new syntax
windowrule = match:class com.libretro.RetroArch, opacity 1 1

# windowrule = idleinhibit fullscreen, class:com.libretro.RetroArch
# new syntax
windowrule = match:class com.libretro.RetroArch, idle_inhibit on fullscreen on

