# Float Steam
# windowrule = float, class:steam
# new syntax
windowrule = match:class steam, float on

# windowrule = center, class:steam, title:Steam
# new syntax
windowrule = match:class steam match:titleSteam, center on

# windowrule = opacity 1 1, class:steam
# new syntax
windowrule = match:class steam, opacity 1 1

# windowrule = size 1100 700, class:steam, title:Steam
# new syntax
windowrule = match:class steam match:title Steam, size 1100 700

# windowrule = size 460 800, class:steam, title:Friends List
# new syntax

windowrule = match:class steam match:title Friends List, size 460 800
# windowrule = idleinhibit fullscreen, class:steam
# new syntax
windowrule = match:class steam, idle_inhibit fullscreen,
