# Define terminal tag to style them uniformly
# windowrule = tag +terminal, class:(Alacritty|kitty|com.mitchellh.ghostty)

#new syntax
windowrule = match:class (Alacritty|kitty|com.mitchellh.ghostty), tag +terminal
