# Webcam overlay for screen recording
# windowrule = float, title:WebcamOverlay
#new syntax
windowrule = match:title WencamOverlay, float on

# windowrule = pin, title:WebcamOverlay
# new syntax
windowrule = match:title WebcamOverlay, pin on

# windowrule = noinitialfocus, title:WebcamOverlay
# new syntax
windowrule = match:title WebcamOverlay, no_initial_focus on

# windowrule = nodim, title:WebcamOverlay
# new syntax
windowrule = match:title WebcamOverlay, no_dim on

# windowrule = move 100%-w-40 100%-w-40, title:WebcamOverlay
#new syntax
windowrule = match:title WebcamOverlay, move 100%-w-40 100%-w-40

# There's a typo in the hyprland rule so 100%-w on the height param is actually correct here
