# Float LocalSend and fzf file picker
# windowrule = float, class:(Share|localsend)
# new syntax
windowrule = match:class (Share|localsend), float on

# windowrule = center, class:(Share|localsend)
# new syntax
windowrule = match:class (Share|localsend), center on

